name: Build and Test

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

env:
  NPM_CONFIG_FUND: '0'
  NPM_CONFIG_AUDIT: '0'
  SUPPRESS_SUPPORT: '1'
  NO_UPDATE_NOTIFIER: 'true'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node:
          - name: LTS
            version: lts/*
          - name: Previous LTS
            version: lts/-1
          - name: Current
            version: node
    name: 'Build and test (Node: ${{ matrix.node.name }})'
    permissions:
      contents: read
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            github.com:443
            objects.githubusercontent.com:443
            nodejs.org:443
            registry.npmjs.org:443

      - name: Check out the code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Set up Node.js environment
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
        with:
          node-version: ${{ matrix.node.version }}
          cache: npm

      - name: Install dependencies
        run: npm ci --ignore-scripts
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run postinstall scripts
        run: npm rebuild && npm run prepare --if-present

      - name: Run tests
        run: npm run test:coverage
